
# Use an official Node.js 14 image as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
ADD package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
ADD . .

# Expose the port on which your application will run
EXPOSE 3000
EXPOSE 80
# Expose additional ports
EXPOSE 3000
EXPOSE 8080
CMD ['npm', 'start', 'app.js']
