
# Base image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
ADD requirements.txt /app/requirements.txt
RUN pip3.8 install --no-cache-dir -r requirements.txt

# Expose ports based on the database type

EXPOSE 3306

# Default port for the application
EXPOSE 8000

# Define environment variable
ENV NAME 555

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
